<?php

namespace Needly\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuestBookEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestBookEntryRepository extends EntityRepository
{
}
